export const ControlPosition = {
    TOP_LEFT : 'TOP_LEFT',
    TOP_CENTER : 'TOP_CENTER',
    TOP_RIGHT : 'TOP_RIGHT',

    LEFT_TOP : 'LEFT_TOP',
    LEFT_CENTER : 'LEFT_CENTER',
    LEFT_BOTTOM : 'LEFT_BOTTOM',

    RIGHT_TOP : 'RIGHT_TOP',
    RIGHT_CENTER : 'RIGHT_CENTER',
    RIGHT_BOTTOM : 'RIGHT_BOTTOM',

    BOTTOM_CENTER : 'BOTTOM_CENTER',
    BOTTOM_LEFT : 'BOTTOM_LEFT',
    BOTTOM_RIGHT : 'BOTTOM_RIGHT',
}
